Holidays for Georgia(Country)
commenthol/date-holidays pull request #190
Opened 2021-01-20 16:15 UTC by scor1on

2021-01-20 19:04 UTC, gerryster requested changes
Thanks for your contribution! I added one minor comment regarding attribution. Feel free to add yourself to the contributors section of package.json. I am going to assign this PR to @commenthol in case he wants to take a look.

2021-01-20 19:04 UTC, gerryster commented on data/countries/GE.yaml
> +  # @source https://en.wikipedia.org/wiki/Public_holidays_in_Georgia_(country)
Please change @source to @attrib. This allows us to comply with Wikipedia's Creative Commons Attribution licensing so these links will automatically be added to the [license file](https://github.com/commenthol/date-holidays/blob/6f588c7ae9c83bcd35b869e2d75f10c47d7f726f/LICENSE). @source is intended for primary sources.

2021-01-20 19:30 UTC, commenthol approved these changes

2021-01-20 19:32 UTC, commenthol commented
@scor1on Thanks for your great contribution. Please update the attribution then we are ready to merge.

2021-01-21 06:17 UTC, scor1on commented on data/countries/GE.yaml
> +  # @source https://en.wikipedia.org/wiki/Public_holidays_in_Georgia_(country)
Done

2021-01-23 13:35 UTC, merged

2021-01-23 13:35 UTC, commenthol commented
@scor1on Thanks for you contribution